// must setting env -> local
# 회원가입 API

POST {{HOST}}:{{PORT}}/api/user/join
content-type: application/json

{
  "memberId": "qkrtkdwns3410",
  "password": "23ia*923oSDHnK#",
  "nickname": "김밥천국지배자",
  "phoneNumber": "010-1234-5678",
  "name": "박상준",
  "email": "qkrtkdwns@naver.com"
}

###
# 회원 업데이트 API
PUT {{HOST}}:{{PORT}}/api/user/{{MEMBER_ID}}
content-type: application/json

{
  "password": "youneedNewPassword",
  "nickname": "김밥천국지배자(수정)",
  "phoneNumber": "010-9999-9999",
  "email": "qkrtkdwnsupdated@naver.com"
}

###
# 회원 목록 출력 API
GET {{HOST}}:{{PORT}}/api/user/list?page=0&size=10&sort=createdDate,desc