spring:
  jpa:
    # https://velog.io/@qkrtkdwns3410/Spring-open-in-view-%EC%86%8D%EC%84%B1 ->  the reason why open-in-view is false
    open-in-view: false
  application:
    name: commerce-submit
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080